AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: 'AWS CloudFormation to create an IAM User with the required permissions to create the FHIR Solution'
Resources:
  FHIRUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
      - PolicyName: FHIR_policy
        PolicyDocument: #Note: this is the same as iam_policy.json
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                -  'cloudwatch:*'
                -  'dynamodb:*'
                -  'events:*'
                -  'iam:*'
                -  'lambda:*'
                -  'logs:*'
                -  's3:*'
                -  'xray:PutTelemetryRecords'
                -  'xray:PutTraceSegments'
                -  'tag:GetResources'
                -  'logs:*'
                -  'cognito-identity:*'
                -  'cognito-idp:*'
                -  'cognito-sync:*'
                -  'es:*'
                -  'cloudformation:*'
                -  'kms:*'
                -  'states:*'
                -  'backup:*'
                -  'backup-storage:MountCapsule'
              Resource: '*'
            - Effect: Allow
              Action:
                -  'apigateway:*'
              Resource:  'arn:aws:apigateway:*::/*'

  CFNKeys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'FHIRUser'


Outputs:
  IAMUserARN:
    Value: !GetAtt 'FHIRUser.Arn'
    Description: IAM User ARN
  AccessKey:
    Value: !Ref 'CFNKeys'
    Description: AWSAccessKeyId of new user
  SecretKey:
    Value: !GetAtt [CFNKeys, SecretAccessKey]
    Description: AWSSecretAccessKey of new user
  MyStacksRegion:
    Value: !Ref 'AWS::Region'
    Description: The Deployed AWS Region
