#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

Resources:
  DDBToESErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reaon: 'We want to explicitly create an alarm name'
    Properties:
      AlarmDescription: Alarm when the Stream errors is more than 1 unit for 15 minutes out of the past 25 minutes. Streams do have retry logic
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, High, DDBToESLambdaErrorAlarm]]
      ActionsEnabled: False
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref DdbToEsLambdaFunction
      Namespace: AWS/Lambda
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      Unit: Count
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  DDBToESIteratorAgeAlarm:
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Properties:
      AlarmDescription: Alarm if the oldest record in the batch when processed was older than 1 minute.
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, High, DDBToESIteratorAgeAlarm]]
      ActionsEnabled: False
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      MetricName: IteratorAge
      Dimensions:
        - Name: FunctionName
          Value: !Ref DdbToEsLambdaFunction
      Namespace: AWS/Lambda
      Period: 300
      Statistic: Average
      Threshold: 60
      TreatMissingData: notBreaching
      Unit: Seconds
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  DdbToEsDLQDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Properties:
      AlarmDescription: Alarm if queue depth increases to >= 1 messages
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, High, DDBToESDLQDepthAlarm]]
      ActionsEnabled: False
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        - Name: QueueName
          Value: !GetAtt DdbToEsDLQ.QueueName
      Namespace: AWS/SQS
      Period: 300
      Statistic: Sum
      Threshold: 0
      Unit: Count
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  FhirLambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Properties:
      AlarmDescription: Alarm when Fhir errors is more than 1
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, High, FhirLambdaErrorAlarm]]
      ActionsEnabled: False
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref FhirServerLambdaFunction
      Namespace: AWS/Lambda
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      Unit: Count
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  FhirLambdaLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Properties:
      AlarmDescription: Alarm when Fhir average latency is more than 2.5s; 2 times
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, Low, FhirLambdaLatencyAlarm]]
      ActionsEnabled: False
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 2
      MetricName: Duration
      Dimensions:
        - Name: FunctionName
          Value: !Ref FhirServerLambdaFunction
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Average
      Threshold: 2500
      TreatMissingData: notBreaching
      Unit: Milliseconds
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  ApiGateway5XXErrorAlarm:
    DependsOn: ApiGatewayRestApi
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Properties:
      AlarmDescription: Alarm when Api GW has more than 1 5xx errors; 3 times
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, High, ApiGateway5XXErrorAlarm]]
      ActionsEnabled: False
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      MetricName: 5XXError
      Dimensions:
        - Name: ApiName
          Value: !Join ['-', [!Ref Stage, '${self:service}']]
      Namespace: AWS/ApiGateway
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      Unit: Count
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  ApiGateway4XXErrorAlarm:
    DependsOn: ApiGatewayRestApi
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Properties:
      AlarmDescription: Alarm when Api GW has more than 1 4xx errors; 3 times
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, Low, ApiGateway4XXErrorAlarm]]
      ActionsEnabled: False
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      MetricName: 4XXError
      Dimensions:
        - Name: ApiName
          Value: !Join ['-', [!Ref Stage, '${self:service}']]
      Namespace: AWS/ApiGateway
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      Unit: Count
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  ApiGatewayLatencyAlarm:
    DependsOn: ApiGatewayRestApi
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Properties:
      AlarmDescription: Alarm when Api GW average latency is more than 3s; 2 times
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, Low, ApiGatewayLatencyAlarm]]
      ActionsEnabled: False
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 2
      MetricName: Latency
      Dimensions:
        - Name: ApiName
          Value: !Join ['-', [!Ref Stage, '${self:service}']]
      Namespace: AWS/ApiGateway
      Period: 60
      Statistic: Average
      Threshold: 3000
      TreatMissingData: notBreaching
      Unit: Milliseconds
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  ClusterStatusRedAlarm:
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Properties:
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, High, FhirESClusterStatusRedAlarm]]
      AlarmDescription: 'Primary and replica shards of at least one index are not allocated to nodes in a cluster.'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value: !Ref ElasticSearchDomain
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      MetricName: 'ClusterStatus.red'
      Namespace: 'AWS/ES'
      Period: 60
      Statistic: Maximum
      Threshold: 0
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  ClusterStatusYellowAlarm:
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Condition: isNotDev
    Properties:
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, Low, FhirESClusterStatusYellowAlarm]]
      AlarmDescription: 'Replica shards for at least one index are not allocated to 2 nodes in a cluster.'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value: !Ref ElasticSearchDomain
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      MetricName: 'ClusterStatus.yellow'
      Namespace: 'AWS/ES'
      Period: 60
      Statistic: Maximum
      Threshold: 0
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  ClusterCPUUtilizationTooHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Properties:
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, High, FhirESClusterCPUUtilAlarm]]
      AlarmDescription: 'Average CPU utilization over last 10 minutes too high.'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value: !Ref ElasticSearchDomain
      EvaluationPeriods: 1
      MetricName: 'CPUUtilization'
      Namespace: 'AWS/ES'
      Period: 600
      Statistic: Average
      Threshold: 80
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  ClusterMasterCPUUtilizationTooHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Condition: isNotDev
    Properties:
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, Low, FhirESClusterMasterCPUUtilAlarm]]
      AlarmDescription: 'Average CPU utilization over last 10 minutes too high.'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value: !Ref ElasticSearchDomain
      EvaluationPeriods: 1
      MetricName: 'MasterCPUUtilization'
      Namespace: 'AWS/ES'
      Period: 600
      Statistic: Average
      Threshold: 50
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  ClusterFreeStorageSpaceTooLowAlarm:
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Properties:
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, Low, FhirESClusterFreeStorageSpaceTooLowAlarm]]
      AlarmDescription: 'Cluster is running out of storage space.'
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value: !Ref ElasticSearchDomain
      EvaluationPeriods: 1
      MetricName: 'FreeStorageSpace'
      Namespace: 'AWS/ES'
      Period: 60
      Statistic: Minimum
      Threshold: !If [isDev, 2500, 22500] # in MB; aiming for alarm at 25% remaining
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  ClusterIndexWritesBlockedTooHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Properties:
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, Low, FhirESClusterIndexWritesBlockedTooHighAlarm]]
      AlarmDescription: 'Cluster is blocking incoming write requests.'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value: !Ref ElasticSearchDomain
      EvaluationPeriods: 1
      MetricName: 'ClusterIndexWritesBlocked'
      Namespace: 'AWS/ES'
      Period: 60
      Statistic: Maximum
      Threshold: 0
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  ClusterJVMMemoryPressureTooHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Properties:
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, Low, FhirESClusterJVMMemoryAlarm]]
      AlarmDescription: 'Average JVM memory pressure over last 10 minutes too high.'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value: !Ref ElasticSearchDomain
      EvaluationPeriods: 1
      MetricName: 'JVMMemoryPressure'
      Namespace: 'AWS/ES'
      Period: 600
      Statistic: Average
      Threshold: 80
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  ClusterMasterJVMMemoryPressureTooHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Condition: isNotDev
    Properties:
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, Low, FhirESClusterMasterJVMMemoryAlarm]]
      AlarmDescription: 'Average JVM memory pressure over last 10 minutes too high.'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value: !Ref ElasticSearchDomain
      EvaluationPeriods: 1
      MetricName: 'MasterJVMMemoryPressure'
      Namespace: 'AWS/ES'
      Period: 600
      Statistic: Average
      Threshold: 80
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  ClusterMasterNotReachableFromNodeAlarm:
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Condition: isNotDev
    Properties:
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, Low, FhirESClusterMasterNotReachableFromNodeAlarm]]
      AlarmDescription: 'Master node stopped or not reachable. Usually the result of a network connectivity issue or AWS dependency problem.'
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value: !Ref ElasticSearchDomain
      EvaluationPeriods: 5
      MetricName: 'MasterReachableFromNode'
      Namespace: 'AWS/ES'
      Period: 60
      Statistic: Minimum
      Threshold: 1
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  ClusterAutomatedSnapshotFailureTooHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Condition: isNotDev
    Properties:
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, Low, FhirESClusterSnapshotFailureAlarm]]
      AlarmDescription: 'No automated snapshot was taken for the domain in the previous 36 hours.'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value: !Ref ElasticSearchDomain
      EvaluationPeriods: 1
      MetricName: 'AutomatedSnapshotFailure'
      Namespace: 'AWS/ES'
      Period: 60
      Statistic: Maximum
      Threshold: 0
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  ClusterKibanaHealthyNodesTooLowAlarm:
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Condition: isDev
    Properties:
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, Low, FhirESClusterKibanaAlarm]]
      AlarmDescription: 'Kibana is inaccessible.'
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value: !Ref ElasticSearchDomain
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      MetricName: 'KibanaHealthyNodes'
      Namespace: 'AWS/ES'
      Period: 60
      Statistic: Minimum
      Threshold: 1
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  ClusterKMSKeyErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Properties:
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, High, FhirESClusterKMSErrorAlarm]]
      AlarmDescription: 'KMS customer master key used to encrypt data at rest has been disabled.'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value: !Ref ElasticSearchDomain
      EvaluationPeriods: 1
      MetricName: 'KMSKeyError'
      Namespace: 'AWS/ES'
      Period: 60
      Statistic: Maximum
      Threshold: 0
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  ClusterKMSKeyInaccessibleAlarm:
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Properties:
      AlarmName: !Join ['.', [FhirSolution, !Ref Stage, High, FhirESClusterKMSInaccessibleAlarm]]
      AlarmDescription: 'KMS customer master key used to encrypt data at rest has been deleted or revoked its grants to Amazon ES.'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value: !Ref ElasticSearchDomain
      EvaluationPeriods: 1
      MetricName: 'KMSKeyInaccessible'
      Namespace: 'AWS/ES'
      Period: 60
      Statistic: Maximum
      Threshold: 0
      OKActions:
        - !Ref FhirWorksAlarmSNSTopic
      AlarmActions:
        - !Ref FhirWorksAlarmSNSTopic
  FhirWorksAlarmSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Join ['-', [FhirSolution, !Ref Stage, cloudwatch, alarm, topic]]
      KmsMasterKeyId: !Ref SnsKMSKey
  FhirWorksAlarmSNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    DependsOn: FhirWorksAlarmSNSTopic
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: FhirWorksAlarmSNSTopicPolicy
            Effect: Allow
            Principal:
              Service: 'cloudwatch.amazonaws.com'
            Action:
              - sns:Publish
            Resource: !Ref FhirWorksAlarmSNSTopic
      Topics:
        - !Ref FhirWorksAlarmSNSTopic
