#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

Resources:
  FhirLambdaErrorAlarm:
    DependsOn: FhirServerLambdaFunction
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarm when Fhir errors is more than 1
      AlarmName: FhirSolution.${self:custom.stage}.High.FhirLambdaErrorAlarm
      ActionsEnabled: False
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref FhirServerLambdaFunction
      Namespace: AWS/Lambda
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      Unit: Count
  FhirLambdaLatencyAlarm:
    DependsOn: FhirServerLambdaFunction
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarm when Fhir average latency is more than 2.5s; 2 times
      AlarmName: FhirSolution.${self:custom.stage}.Low.FhirLambdaLatencyAlarm
      ActionsEnabled: False
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 2
      MetricName: Duration
      Dimensions:
        - Name: FunctionName
          Value: !Ref FhirServerLambdaFunction
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Average
      Threshold: 2500
      TreatMissingData: notBreaching
      Unit: Milliseconds
  ApiGateway5XXErrorAlarm:
    DependsOn: ApiGatewayRestApi
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarm when Api GW has more than 1 5xx errors; 3 times
      AlarmName: FhirSolution.${self:custom.stage}.High.ApiGateway5XXErrorAlarm
      ActionsEnabled: False
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      MetricName: 5XXError
      Dimensions:
        - Name: ApiName
          Value: ${self:custom.stage}-${self:service}
      Namespace: AWS/ApiGateway
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      Unit: Count
  ApiGateway4XXErrorAlarm:
    DependsOn: ApiGatewayRestApi
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarm when Api GW has more than 1 4xx errors; 3 times
      AlarmName: FhirSolution.${self:custom.stage}.Low.ApiGateway4XXErrorAlarm
      ActionsEnabled: False
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 3
      MetricName: 4XXError
      Dimensions:
        - Name: ApiName
          Value: ${self:custom.stage}-${self:service}
      Namespace: AWS/ApiGateway
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
      Unit: Count
  ApiGatewayLatencyAlarm:
    DependsOn: ApiGatewayRestApi
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarm when Api GW average latency is more than 3s; 2 times
      AlarmName: FhirSolution.${self:custom.stage}.Low.ApiGatewayLatencyAlarm
      ActionsEnabled: False
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 2
      MetricName: Latency
      Dimensions:
        - Name: ApiName
          Value: ${self:custom.stage}-${self:service}
      Namespace: AWS/ApiGateway
      Period: 60
      Statistic: Average
      Threshold: 3000
      TreatMissingData: notBreaching
      Unit: Milliseconds
