#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

Resources:
  FHIRServicePrivate:
    Type: AWS::ApiGateway::RestApi
    Condition: isUsingPrivateApi
    DependsOn:
      - ApiGatewayRestApi
      - ApiGatewayMethodMetadataGet
      - FhirServerLambdaFunction
      - FhirServerProvConcLambdaAlias
    Properties:
      Name: !Join ['-', [!Ref Stage, fhir, service, private]]
      Description: "Private FHIR API Server"
      CloneFrom: !Ref ApiGatewayRestApi
      EndpointConfiguration:
        Types:
          - PRIVATE
      Policy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 'execute-api:Invoke'
            Resource: 'execute-api:/*/*/*'
            Condition: 
              StringEquals:
                  "aws:PrincipalOrgID": !Sub '${self:custom.privateOrgId}'
  
  FHIRServiceStageDeployment:
    Type: AWS::ApiGateway::Deployment
    Condition: isUsingPrivateApi
    DependsOn:
      - FHIRServicePrivate
      - FhirServerLambdaFunction
      - FhirServerProvConcLambdaAlias
    Properties: 
      RestApiId: !Ref FHIRServicePrivate
      StageName: !Ref Stage
      StageDescription:
        AccessLogSetting:
          DestinationArn: !GetAtt ApiGatewayLogGroup.Arn
          Format: ${self:provider.logs.restApi.format}
        TracingEnabled: ${self:provider.tracing.apiGateway}
        # the below */* method settings are explicitly being set by serverless
        # however defaults match in API gateway and for an unknnown reason 
        # serverless deploy is failing when setting them
        #MethodSettings:
        #  - CacheDataEncrypted: true
        #    CacheTtlInSeconds: '300'
        #    CachingEnabled: false
        #    DataTraceEnabled: true
        #    HttpMethod: "*"
        #    LoggingLevel: "OFF"
        #    MetricsEnabled: false
        #    ResourcePath: "*"
        #    ThrottlingBurstLimit: '5000'
        #    ThrottlingRateLimit: '10000.0'

  #FHIRServicePrivateStage:
  #  Type: AWS::ApiGateway::Stage
  #  Condition: isUsingPrivateApi
  #  DependsOn:
  #    - FHIRServicePrivate
  #    - FhirServerLambdaFunction
  #    - FhirServerProvConcLambdaAlias
  #    - FHIRServiceStageDeployment
  #  Properties:
  #    RestApiId: !Ref FHIRServicePrivate
  #    StageName: !Ref Stage
  #    DeploymentId: !Ref FHIRServiceStageDeployment
  #    AccessLogSetting:
  #     DestinationArn: !GetAtt FHIRLogsBucket.Arn
  #     Format: ${self:provider.logs.restApi.format}
  #    TracingEnabled: ${self:provider.tracing.apiGateway}

  FHIRServicePrivateLambdaPermission:
    Type: AWS::Lambda::Permission
    Condition: isUsingPrivateApi
    DependsOn:
      - FHIRServicePrivate
      - FhirServerLambdaFunction
      - FhirServerProvConcLambdaAlias
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref FhirServerProvConcLambdaAlias
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Join ['', ['arn:', !Sub "${AWS::Partition}", ':execute-api:', !Sub "${AWS::Region}", ':', !Sub "${AWS::AccountId}", ':', !Ref FHIRServicePrivate, '/*/*']]

  FHIRServicePrivateUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - FHIRServiceStageDeployment
    Properties: 
      ApiStages: 
        - ApiId: !Ref FHIRServicePrivate
          Stage: !Ref Stage
      Description: !Join ['', ['Usage plan for ', !Join ['-', [!Ref Stage, fhir, service, private]], ' ', !Ref Stage, ' stage']]
      #Tags: ${self.provider.stackTags}
      Throttle:
        BurstLimit: ${self:provider.usagePlan.throttle.burstLimit}
        RateLimit: ${self:provider.usagePlan.throttle.rateLimit}
      UsagePlanName: !Join ['-', [!Ref Stage, fhir, service, private]]
  
  FHIRServicePrivateUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties: 
      KeyId: !Ref ApiGatewayApiKey1
      KeyType: API_KEY
      UsagePlanId: !Ref FHIRServicePrivateUsagePlan