#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

# NOTE: this is an extra Cloudformation stack; not linked to FHIR Server stack
Description: '(SO0128) - Solution - Backup Plan Template - This template creates resources necessary to back up all resources tagged with backup=daily daily at 5am UTC.'
Resources:
  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: 'Encryption key for daily'
      EnableKeyRotation: True
      Enabled: True
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              'AWS': { 'Fn::Sub': 'arn:${AWS::Partition}:iam::${AWS::AccountId}:root' }
            Action:
              - kms:*
            Resource: '*'

  BackupVaultWithDailyBackups:
    Type: 'AWS::Backup::BackupVault'
    Properties:
      BackupVaultName: 'BackupVaultWithDailyBackups'
      EncryptionKeyArn: !GetAtt KMSKey.Arn

  BackupPlanWithDailyBackups:
    Type: 'AWS::Backup::BackupPlan'
    Properties:
      BackupPlan:
        BackupPlanName: 'BackupPlanWithDailyBackups'
        BackupPlanRule:
          - RuleName: 'RuleForDailyBackups'
            TargetBackupVault: !Ref BackupVaultWithDailyBackups
            ScheduleExpression: 'cron(0 5 ? * * *)'

  BackupRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'backup.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForRestores'

  TagBasedBackupSelection:
    Type: 'AWS::Backup::BackupSelection'
    Properties:
      BackupSelection:
        SelectionName: 'TagBasedBackupSelection'
        IamRoleArn: !GetAtt BackupRole.Arn
        ListOfTags:
          - ConditionType: 'STRINGEQUALS'
            ConditionKey: 'backup'
            ConditionValue: 'daily'
          - ConditionType: 'STRINGEQUALS'
            ConditionKey: 'service'
            ConditionValue: 'fhir'
      BackupPlanId: !Ref BackupPlanWithDailyBackups
