#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

Resources:
  GlueJobRelatedLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      Policies:
        - PolicyName: glueAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                  - glue:GetJobRun
                  - glue:BatchStopJobRun
                Resource: '*'
              - Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:GetItem
                Resource:
                  - !GetAtt ExportRequestDynamoDBTable.Arn
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource:
                  - !GetAtt DynamodbKMSKey.Arn

  GlueScriptsBucket:
    Type: AWS::S3::Bucket

  BulkExportResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - Id: ExpirationRule
            Status: Enabled
            ExpirationInDays: '3'

  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: ddbAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DescribeTable
                  - dynamodb:Scan
                Resource: !GetAtt ResourceDynamoDBTableV2.Arn
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource:
                  - !GetAtt DynamodbKMSKey.Arn
        - PolicyName: s3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Join ['', ['arn:aws:s3:::', !Ref BulkExportResultsBucket, '/*']]
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Join ['', ['arn:aws:s3:::', !Ref GlueScriptsBucket, '/*']]

  ExportGlueJob:
    Type: AWS::Glue::Job
    DependsOn: UploadGlueScriptsCustomResource
    Properties:
      Role: !GetAtt GlueJobRole.Arn
      GlueVersion: '2.0'
      WorkerType: !Ref ExportGlueWorkerType
      NumberOfWorkers: !Ref ExportGlueNumberWorkers
      Command:
        ScriptLocation: !Join ['', ['s3://', !Ref GlueScriptsBucket, '/export-script.py']]
        Name: glueetl
        PythonVersion: '3'
      ExecutionProperty:
        MaxConcurrentRuns: 2
      DefaultArguments:
        '--TempDir': !Join ['', ['s3://', !Ref BulkExportResultsBucket, '/temp']]
        '--ddbTableName': '${self:custom.resourceTableName}'
        '--workerType': !Ref ExportGlueWorkerType
        '--numberWorkers': !Ref ExportGlueNumberWorkers
        '--s3OutputBucket': !Ref BulkExportResultsBucket
        '--enable-metrics': 'true'
        '--enable-continuous-cloudwatch-log': 'true'
        '--enable-continuous-log-filter': 'true'

  ExportResultsSignerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: s3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Join ['', [!GetAtt BulkExportResultsBucket.Arn, '/*']]

  UpdateStatusLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      Policies:
        - PolicyName: ddbAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:UpdateItem
                Resource:
                  - !GetAtt ExportRequestDynamoDBTable.Arn
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource:
                  - !GetAtt DynamodbKMSKey.Arn

  UploadGlueScriptsCustomResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt UploadGlueScriptsLambdaFunction.Arn # serverless by convention capitalizes first letter and suffixes with "LambdaFunction"
      RandomValue: ${sls:instanceId} # This forces the upload to happen on every deployment

  UploadGlueScriptsLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      Policies:
        - PolicyName: s3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Join ['', ['arn:aws:s3:::', !Ref GlueScriptsBucket, '/*']]
