#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      AutoVerifiedAttributes:
        - email
      UserPoolName: !Ref AWS::StackName
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true
        - AttributeDataType: String
          Name: cc_confirmed
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      ClientName: !Sub '${AWS::StackName}-UserPool'
      UserPoolId: !Ref UserPool
      CallbackURLs:
        - !Ref CognitoOAuthDefaultRedirectURL
      DefaultRedirectURI: !Ref CognitoOAuthDefaultRedirectURL
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - COGNITO
      PreventUserExistenceErrors: ENABLED
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref UserPoolClient
      UserPoolId: !Ref UserPool
  PractitionerUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: This is a member of the hospital staff, who directly helps patients
      GroupName: practitioner
      Precedence: 0
      UserPoolId: !Ref UserPool
  NonPractitionerUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: This is a member of the hospital staff who needs access to non-medical record
      GroupName: non-practitioner
      Precedence: 1
      UserPoolId: !Ref UserPool
  AuditorUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Someone who needs read, v_read and search access on patients
      GroupName: auditor
      Precedence: 2
      UserPoolId: !Ref UserPool
