#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

Resources:
  S3Alias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/s3Key-${self:custom.stage}'
      TargetKeyId:
        Ref: S3KMSKey
  S3KMSKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      Description: 'KMS CMK for s3'
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: 'Enable IAM Root Permissions'
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Fn::If:
              - isDev
              - Sid: 'Enable IAM User Permissions'
                Effect: Allow
                Principal:
                  AWS: ${self:custom.config.devAwsUserAccountArn}
                Action: 'kms:*'
                Resource: '*'
              - Ref: AWS::NoValue
  DynamodbAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/dynamoKey-${self:custom.stage}'
      TargetKeyId:
        Ref: DynamodbKMSKey
  DynamodbKMSKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      Description: 'KMS CMK for DynamoDB'
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: 'Enable IAM Root Permissions'
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Fn::If:
              - isDev
              - Sid: 'Enable IAM User Permissions'
                Effect: Allow
                Principal:
                  AWS: ${self:custom.config.devAwsUserAccountArn}
                Action: 'kms:*'
                Resource: '*'
              - Ref: AWS::NoValue
  ElasticSearchAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/elasticKey-${self:custom.stage}'
      TargetKeyId:
        Ref: ElasticSearchKMSKey
  ElasticSearchKMSKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      Description: 'KMS CMK for Elastic Search'
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: 'Enable IAM Root Permissions'
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Fn::If:
              - isDev
              - Sid: 'Enable IAM User Permissions'
                Effect: Allow
                Principal:
                  AWS: ${self:custom.config.devAwsUserAccountArn}
                Action: 'kms:*'
                Resource: '*'
              - Ref: AWS::NoValue
