#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

Resources:
  S3Alias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Join ['-', [alias/s3Key, !Ref Stage]]
      TargetKeyId: !Ref S3KMSKey
  S3KMSKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      Description: 'KMS CMK for s3'
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: 'Enable IAM Root Permissions'
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
  DynamodbAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Join ['-', [alias/dynamoKey, !Ref Stage]]
      TargetKeyId: !Ref DynamodbKMSKey
  DynamodbKMSKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      Description: 'KMS CMK for DynamoDB'
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: 'Enable IAM Root Permissions'
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
  ElasticSearchAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Join ['-', [alias/elasticKey, !Ref Stage]]
      TargetKeyId: !Ref ElasticSearchKMSKey
  ElasticSearchKMSKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      Description: 'KMS CMK for Elastic Search'
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: 'Enable IAM Root Permissions'
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
  LogAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Join ['-', [alias/logKey, !Ref Stage]]
      TargetKeyId: !Ref LogKMSKey
  LogKMSKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      Description: 'KMS CMK for Cloudwatch Logs'
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: 'Enable IAM Root Permissions'
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: 'Allow Cloudwatch to use this Key policy'
            Effect: Allow
            Principal:
              Service: !Sub logs.${AWS::Region}.amazonaws.com
            Action:
              - kms:Encrypt*
              - kms:Decrypt*
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:Describe*
            Resource: '*'
            Condition:
              ArnLike:
                kms:EncryptionContext:aws:logs:arn: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*

