name: Unit Tests and Deploy
on:
  push:
    branches:
      - mainline
jobs:
  unit-test:
    name: Unit Test and Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: |
          cd auditLogMover
          yarn install
          cd ..
          yarn install
      - name: Lint
        run: |
          cd auditLogMover
          yarn lint
          cd ..
          yarn lint
      - name: Unit tests
        run: yarn test
  deploy:
    needs: unit-test
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup config file
        env:
          DEV_AWS_USER_ACCOUNT_ARN: ${{ secrets.devAwsUserAccountArn }}
        run: sed "s#<dev-arn>#$DEV_AWS_USER_ACCOUNT_ARN#g" serverless_config.template.json > serverless_config.json
      - name: Install serverless
        run: npm install -g serverless
      - name: Deploy FHIR Server and ddbToEs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          yarn install
          serverless deploy --stage dev --region us-west-2 --conceal
      - name: Deploy auditLogMover
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd auditLogMover
          yarn install
          serverless deploy --stage dev --region us-west-2 --conceal